name: Appium Tests

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [34]
        target: [google_apis]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Flutter Submodule
        run: |
          git submodule update --init --recursive
          cd submodules/flutter
          git reset --merge
          git checkout stable
          git pull origin stable
          cd ../..

      - name: Install Flutter dependencies
        run: submodules/flutter/bin/flutter pub get

      - name: Create key.properties placeholder
        run: |
          echo "storePassword=debug" > android/key.properties
          echo "keyPassword=debug" >> android/key.properties
          echo "keyAlias=debug" >> android/key.properties
          echo "storeFile=debug" >> android/key.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK
        run: submodules/flutter/bin/flutter build apk --flavor pro --debug

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Appium and dependencies
        run: |
          npm install -g appium
          npm install -g appium-doctor
          appium-doctor --android
          appium -v
          appium &>/dev/null &

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          script: cd appium && ./gradlew test --info

